MC-11 Settings presentation
k0dm/Frankfurter pull request #10
Opened 2024-03-01 17:52 UTC by k0dm

2024-03-01 18:11 UTC, JohnnySC requested changes

2024-03-01 18:11 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/CurrencyUi.kt
> +        chosenImageView.also { if (chosen) it.show() else it.hide() }
run

2024-03-01 18:11 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/adapter/CurrencyAdapter.kt
> +    private val currencies = mutableListOf<CurrencyUi>()
fun selected() : String = currencies.find {it.isselected}?:""

2024-03-01 18:11 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/SettingsUiState.kt
> +    fun show(
fun show(saveButton)

2024-03-01 18:11 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/adapter/CurrencyAdapter.kt
> +    private val chooseCurrencyBlock: (String) -> Unit
2 types

2024-03-01 18:11 UTC, JohnnySC commented on presentation/src/main/res/layout/fragment_settings.xml
>          android:layout_width="wrap_content"
id

2024-03-01 18:11 UTC, JohnnySC commented on presentation/src/main/res/layout/fragment_settings.xml
> +
<View
background = color/black
width = 1dp
height = match_parent

2024-03-01 18:14 UTC, JohnnySC requested changes

2024-03-01 18:14 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/SettingsViewModel.kt
> +    fun save() = runAsync({
fun save(from:String, to: String)

2024-03-02 15:05 UTC, JohnnySC requested changes

2024-03-02 15:05 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/CurrencyUi.kt
> +            (currencyUi as? Base)?.value == this.value
no need to cast: use value()

2024-03-02 15:05 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/settings/SettingsViewModel.kt
> +                if (isEmpty()) listOf(CurrencyUi.Empty)
maybe mapper?

2024-03-02 19:20 UTC, k0dm commented on presentation/src/main/java/com/example/presentation/settings/CurrencyUi.kt
> +            (currencyUi as? Base)?.value == this.value
fixed

2024-03-02 19:20 UTC, k0dm commented on presentation/src/main/java/com/example/presentation/settings/SettingsViewModel.kt
> +                if (isEmpty()) listOf(CurrencyUi.Empty)
fixed

2024-03-04 14:48 UTC, JohnnySC requested changes

2024-03-04 14:48 UTC, JohnnySC commented on presentation/src/main/java/com/example/presentation/core/UpdateAdapter.kt
> +interface UpdateAdapter<T> {
T: Any

2024-03-04 15:09 UTC, JohnnySC approved these changes

2024-03-04 15:19 UTC, merged